/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LivrariaProjetoPOO.tela;

import LivrariaProjetoPOO.basica.Livro;
import LivrariaProjetoPOO.fachada.LivroFachada;
import LivrariaProjetoPOO.util.Uteis;

/**
 *
 * @author BrunoTiCaVini
 */
public class CadastrarLivro extends javax.swing.JFrame {
    
    public static final String TELA_MODO_EDITAR = "e";
    public static final String TELA_MODO_CADASTRAR = "c";
    public static final String TELA_MODO_VOLTAR = "v";
    
    private LivroFachada livroFachada ;
    
    public String modoTela = "";
    public Livro livro = new Livro();

    /**
     * Creates new form CadastrarLivro
     */
    public CadastrarLivro(String tipoTela , Livro pLivro) {
        initComponents();
        
         modoTela = TELA_MODO_EDITAR;
        
        if (tipoTela.equals(TELA_MODO_CADASTRAR)) {
            lbl_codigo.setVisible(true); 
            txt_codigo.setVisible(true);
            modoTela = TELA_MODO_CADASTRAR;
        }else{
            
            livro = pLivro;
            lbl_tela.setText("Editar livro");
            txt_codigo.setText(Uteis.toString(pLivro.getCodlivro()));
            txt_codigo.setEnabled(true);
            
            txt_titulo.setText(livro.getTituloLivro().toUpperCase());
            txt_autor.setText(livro.getAutorLivro().toUpperCase());
            txt_descricao.setText(livro.getDescricaoLivro().toUpperCase());
            
        }
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lbl_tela = new javax.swing.JLabel();
        lbl_descricao = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        lbl_autor = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 181, 94));

        lbl_tela.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_tela.setForeground(new java.awt.Color(102, 51, 0));
        lbl_tela.setText("Cadastro de livro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(lbl_tela)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_tela)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lbl_descricao.setBackground(new java.awt.Color(240, 181, 94));
        lbl_descricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_descricao.setForeground(new java.awt.Color(102, 51, 0));
        lbl_descricao.setText("Descrição Livro");

        lbl_codigo.setBackground(new java.awt.Color(240, 181, 94));
        lbl_codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_codigo.setForeground(new java.awt.Color(102, 51, 0));
        lbl_codigo.setText("Codigo Livro");

        lbl_titulo.setBackground(new java.awt.Color(240, 181, 94));
        lbl_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(102, 51, 0));
        lbl_titulo.setText("Titulo Livro");

        lbl_autor.setBackground(new java.awt.Color(240, 181, 94));
        lbl_autor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_autor.setForeground(new java.awt.Color(102, 51, 0));
        lbl_autor.setText("Autor Livro");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 51, 0));
        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(102, 51, 0));
        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_autor, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(txt_titulo)
                    .addComponent(txt_descricao)
                    .addComponent(txt_codigo))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_autor)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descricao)
                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        livroFachada = new LivroFachada();

        if ( modoTela.equals(TELA_MODO_CADASTRAR)) {

            
            livro.setCodlivro(txt_codigo.getText().toUpperCase());
            livro.setTituloLivro(txt_titulo.getText().toUpperCase());
            livro.setAutorLivro(txt_autor.getText().toUpperCase());
            livro.setDescricaoLivro(txt_descricao.getText().toUpperCase());
            
            
           

            try {
                livroFachada.salvarLivro(livro);
                Uteis.AlertInfo(this,"Livro cadastrado com sucesso!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this, ex.getMessage());
            }

        }else if (modoTela.equals(TELA_MODO_EDITAR) ){

            try {
                 livro.setCodlivro(txt_codigo.getText().toUpperCase());
                 livro.setTituloLivro(txt_titulo.getText().toUpperCase());
                 livro.setAutorLivro(txt_autor.getText().toUpperCase());
                 livro.setDescricaoLivro(txt_descricao.getText().toUpperCase());

                livroFachada.alterarLivro(livro);
                Uteis.AlertInfo(this,"Livro atualizado com sucesso!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this,ex.getMessage());
            }

        }
        
        txt_codigo.setText("");
        txt_titulo.setText("");
        txt_autor.setText("");
        txt_descricao.setText("");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
          ListarLivro Llivro = new ListarLivro();
          Llivro.setVisible(true);
          this.setVisible(false);
          Runtime.getRuntime().runFinalization();
        
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLivro(CadastrarLivro.TELA_MODO_CADASTRAR, null).setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_tela;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
