/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LivrariaProjetoPOO.tela;


import LivrariaProjetoPOO.basica.LivroOnline;
import LivrariaProjetoPOO.util.Uteis;
import LivrariaProjetoPOO.fachada.LivroOnlineFachada;

/**
 *
 * @author BrunoTiCaVini
 */
public class CadastrarLivroOnline extends javax.swing.JFrame {
    
    public static final String TELA_MODO_EDITAR = "e";
    public static final String TELA_MODO_CADASTRAR = "c";
    public static final String TELA_MODO_VOLTAR = "v";
    
    private LivroOnlineFachada livroonlineFachada ;
    
    public String modoTela = "";    
    public LivroOnline livroonline = new LivroOnline();

    /**
     * Creates new form CadastrarLivro
     */
    public CadastrarLivroOnline(String tipoTela , LivroOnline pLivro) {
        initComponents();
        
         modoTela = TELA_MODO_EDITAR;
        
        if (tipoTela.equals(TELA_MODO_CADASTRAR)) {
            lbl_codigoOnline.setVisible(true); 
            txt_codigoOnline.setVisible(true);
            modoTela = TELA_MODO_CADASTRAR;
        }else{
            
            livroonline = pLivro;
            lbl_tela.setText("Editar livro");
            txt_codigoOnline.setText(Uteis.toString(pLivro.getIdLivroOnline()));
            txt_codigoOnline.setEnabled(true);
            
            txt_tituloOnline.setText(livroonline.getTituloLivro());
            txt_autorOnline.setText(livroonline.getAutorLivro());
            txt_descricaoOnline.setText(livroonline.getDescricaoLivro());
            txt_siteOnline.setText(livroonline.getSiteLivro());
            txt_clubeOnline.setText(livroonline.getClubeLivro());
            
            
        }
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lbl_tela = new javax.swing.JLabel();
        lbl_descricaoOnline = new javax.swing.JLabel();
        txt_descricaoOnline = new javax.swing.JTextField();
        lbl_codigoOnline = new javax.swing.JLabel();
        lbl_tituloOnline = new javax.swing.JLabel();
        txt_codigoOnline = new javax.swing.JTextField();
        txt_tituloOnline = new javax.swing.JTextField();
        lbl_autorOnline = new javax.swing.JLabel();
        txt_autorOnline = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btn_voltarOnline = new javax.swing.JButton();
        lbl_descricao1 = new javax.swing.JLabel();
        lbl_descricao2 = new javax.swing.JLabel();
        lbl_siteOnline = new javax.swing.JLabel();
        txt_siteOnline = new javax.swing.JTextField();
        txt_clubeOnline = new javax.swing.JTextField();
        lbl_clubeOnline = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 181, 94));

        lbl_tela.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_tela.setForeground(new java.awt.Color(102, 51, 0));
        lbl_tela.setText("Cadastro de livros Onlines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(lbl_tela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_tela)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lbl_descricaoOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_descricaoOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_descricaoOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_descricaoOnline.setText("Descrição LivroOnline");

        lbl_codigoOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_codigoOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_codigoOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_codigoOnline.setText("Codigo LivroOnline");

        lbl_tituloOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_tituloOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_tituloOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_tituloOnline.setText("Titulo Livro Online");

        lbl_autorOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_autorOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_autorOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_autorOnline.setText("Autor LivroOnline");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 51, 0));
        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_voltarOnline.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltarOnline.setForeground(new java.awt.Color(102, 51, 0));
        btn_voltarOnline.setText("VOLTAR");
        btn_voltarOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarOnlineActionPerformed(evt);
            }
        });

        lbl_descricao1.setBackground(new java.awt.Color(240, 181, 94));
        lbl_descricao1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_descricao1.setForeground(new java.awt.Color(240, 181, 94));

        lbl_descricao2.setBackground(new java.awt.Color(240, 181, 94));
        lbl_descricao2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_descricao2.setForeground(new java.awt.Color(240, 181, 94));

        lbl_siteOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_siteOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_siteOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_siteOnline.setText("Site LivroOnline");

        lbl_clubeOnline.setBackground(new java.awt.Color(240, 181, 94));
        lbl_clubeOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_clubeOnline.setForeground(new java.awt.Color(102, 51, 0));
        lbl_clubeOnline.setText("Clube LivroOnline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_voltarOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_clubeOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_clubeOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_descricao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_siteOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39)
                                .addComponent(txt_siteOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_tituloOnline)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lbl_codigoOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_descricaoOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_autorOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_autorOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_descricaoOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tituloOnline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_codigoOnline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lbl_descricao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigoOnline)
                    .addComponent(txt_codigoOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tituloOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tituloOnline))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autorOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_autorOnline))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_descricaoOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descricaoOnline))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_siteOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_siteOnline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_descricao1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_clubeOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_clubeOnline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_voltarOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(323, Short.MAX_VALUE)
                    .addComponent(lbl_descricao2)
                    .addGap(167, 167, 167)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        livroonlineFachada = new LivroOnlineFachada();

        if ( modoTela.equals(TELA_MODO_CADASTRAR)) {

            livroonline.setCodlivro(txt_codigoOnline.getText());
            livroonline.setTituloLivro(txt_tituloOnline.getText());
            livroonline.setAutorLivro(txt_autorOnline.getText());
            livroonline.setDescricaoLivro(txt_descricaoOnline.getText());
            livroonline.setSiteLivro(txt_siteOnline.getText());
            livroonline.setClubeLivro(txt_clubeOnline.getText());
            
           

            try {
                livroonlineFachada.salvarLivro(livroonline);
                Uteis.AlertInfo(this,"Livro cadastrado com sucesso!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this, ex.getMessage());
            }

        }else if (modoTela.equals(TELA_MODO_EDITAR) ){

            try {
                 livroonline.setCodlivro(txt_codigoOnline.getText());
                 livroonline.setTituloLivro(txt_tituloOnline.getText());
                 livroonline.setAutorLivro(txt_autorOnline.getText());
                 livroonline.setDescricaoLivro(txt_descricaoOnline.getText());
                 livroonline.setSiteLivro(txt_siteOnline.getText());
                 livroonline.setClubeLivro(txt_clubeOnline.getText());

                livroonlineFachada.alterarLivro(livroonline);
                Uteis.AlertInfo(this,"Livro atualizado com sucesso!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this,ex.getMessage());
            }

        }
        
        txt_codigoOnline.setText("");
        txt_tituloOnline.setText("");
        txt_autorOnline.setText("");
        txt_descricaoOnline.setText("");
        txt_siteOnline.setText("");
        txt_clubeOnline.setText("");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_voltarOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarOnlineActionPerformed
        // TODO add your handling code here:
          ListarLivroOnline LlivroOnline = new ListarLivroOnline();
          LlivroOnline.setVisible(true);
          this.setVisible(false);
          Runtime.getRuntime().runFinalization();
        
    }//GEN-LAST:event_btn_voltarOnlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivroOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivroOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivroOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivroOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLivroOnline(CadastrarLivroOnline.TELA_MODO_CADASTRAR, null).setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltarOnline;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_autorOnline;
    private javax.swing.JLabel lbl_clubeOnline;
    private javax.swing.JLabel lbl_codigoOnline;
    private javax.swing.JLabel lbl_descricao1;
    private javax.swing.JLabel lbl_descricao2;
    private javax.swing.JLabel lbl_descricaoOnline;
    private javax.swing.JLabel lbl_siteOnline;
    private javax.swing.JLabel lbl_tela;
    private javax.swing.JLabel lbl_tituloOnline;
    private javax.swing.JTextField txt_autorOnline;
    private javax.swing.JTextField txt_clubeOnline;
    private javax.swing.JTextField txt_codigoOnline;
    private javax.swing.JTextField txt_descricaoOnline;
    private javax.swing.JTextField txt_siteOnline;
    private javax.swing.JTextField txt_tituloOnline;
    // End of variables declaration//GEN-END:variables
}
